#!/bin/bash

set -eo pipefail

if [[ $# -ne 1 ]]; then
  >&2 echo "Invalid arguments."
  exit 1
fi

if [[ $PACK_REGISTRY_GCR = true ]] || [[ $PACK_REGISTRY_GCR = 1 ]]; then
  echo "Configuring credentials for GCR."
  docker-credential-gcr configure-docker >/dev/null 2>&1
fi

tmp_dir=$(mktemp -d)

mkdir -p "${tmp_dir}/home/vcap"
tar xzf droplet.tgz -C "${tmp_dir}/home/vcap"
chown -R vcap:vcap "${tmp_dir}/home/vcap"

tar czf "${tmp_dir}/layer.tgz" -C "$tmp_dir" home
crane append "$SRC_IMAGE" "$1" "${tmp_dir}/layer.tgz"

rm -rf "$tmp_dir"
