#!/bin/bash

set -euo pipefail

DST_IMAGE="$1"

mkdir -p home/vcap
tar xzf droplet.tgz -C home/vcap
chown -R vcap:vcap home

tar -cvzf layer.tgz home
d8s append "${SRC_IMAGE}" "${DST_IMAGE}" layer.tgz
