ARG stack
ARG go_version=1.10.3

FROM golang:${go_version} as lifecycle
ARG lifecycle_ref=33104de
ARG lifecycle_repo=github.com/sclevine/lifecycle

WORKDIR /go/src/${lifecycle_repo}
RUN git clone --single-branch "https://${lifecycle_repo}" . && \
  git checkout "${lifecycle_ref}"
RUN CGO_ENABLED=0 go install -a -installsuffix static "${lifecycle_repo}/cmd/..."

FROM ${stack}

RUN useradd -u 1000 -mU -s /bin/bash packs
COPY --from=lifecycle /go/bin /packs

WORKDIR /workspace